#!/bin/bash
clear
command -v git >/dev/null 2>&1 || {
    echo -e "\e[33mgit\e[31m not found...\n[ Aborting ]\e[m"
    exit 1;
}
rm $HOME/.zinux -fr
mkdir $HOME/.zinux
chmod 775 $HOME/.zinux -R
cd $HOME/.zinux
echo -e "Starting to cloning \e[33mzinux\e[m..."
echo -e "\e[33m\c"
git clone https://github.com/dariushha/zinux.git
cd zinux
git clone https://github.com/dariushha/zg.git
echo -e "\e[m\c"
cd $HOME/.zinux
echo -e "Modifing \e[33m\$HOME\e[m varibale content ..."
echo '#!/bin/bash
PATH="$HOME/.zinux/zinux/zg/bin:$PATH"' > .bashzg
if ! [ -e .bashzg ]; then
    echo -e "\e[31mCouldn't create \e[33m.bashzg\e[m file!\n[ Aborting ]\e[m" >&2
    exit 1;
fi;
chmod 775 .bashzg
echo -e "Adding \e[33mzg\e[m to \$PATH"
if  ! [ -e $HOME/.bashrc ];then
    echo -e "\e[31m Couldn't find \e[33m$HOME/.bashrc\e[31m; please add following lines in a bash loader file...\e[m" 
    echo 'source $HOME/.zinux/.bashzg'
else 
    command -v zg --version >/dev/null 2>&1 || {
		echo 'source $HOME/.zinux/.bashzg' >> $HOME/.bashrc
    }
fi
source $HOME/.bashrc
cd $HOME
chmod 775 $HOME/.zinux -R
command -v zg --version >/dev/null 2>&1 || {
    echo -e "\e[31mUnable to add \e[33mzg\e[31m to system \$PATH\e[m" >&2
    exit 1;
}
echo -e "\e[33mzg\e[32m installled successfully ...\nYou can test it by \e[33mzg --version\e[32m command ..."
