<?php

namespace iMVC\kernel\security;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-05 at 04:31:23.
 */
class hashTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var hash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new hash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\kernel\security\hash::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\security\hash::generate
     * @todo   Implement testGenerate().
     */
    public function testGenerate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
