<?php

namespace iMVC\mailer\PHPMailer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-05 at 04:42:21.
 */
class gmailMailerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var gmailMailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new gmailMailer("","");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
