<?php

namespace zinux\kernel\layout;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:45.
 */
class baseLayoutTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var baseLayout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new baseLayout;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::Dispose
     * @todo   Implement testDispose().
     */
    public function testDispose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::AddCSS
     * @todo   Implement testAddCSS().
     */
    public function testAddCSS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::AddJS
     * @todo   Implement testAddJS().
     */
    public function testAddJS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::AddMeta
     * @todo   Implement testAddMeta().
     */
    public function testAddMeta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::IsLayoutSuppressed
     * @todo   Implement testIsLayoutSuppressed().
     */
    public function testIsLayoutSuppressed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::RemoveCSS
     * @todo   Implement testRemoveCSS().
     */
    public function testRemoveCSS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::RemoveJS
     * @todo   Implement testRemoveJS().
     */
    public function testRemoveJS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::RemoveMeta
     * @todo   Implement testRemoveMeta().
     */
    public function testRemoveMeta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::Render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::SetDefaultLayout
     * @todo   Implement testSetDefaultLayout().
     */
    public function testSetDefaultLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::SetLayout
     * @todo   Implement testSetLayout().
     */
    public function testSetLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\layout\baseLayout::SuppressLayout
     * @todo   Implement testSuppressLayout().
     */
    public function testSuppressLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
