<?php

namespace zinux\kernel\mvc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:47.
 */
class controllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\mvc\controller::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\mvc\controller::GetNameSpace
     * @todo   Implement testGetNameSpace().
     */
    public function testGetNameSpace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\mvc\controller::CheckControllerExists
     * @todo   Implement testCheckControllerExists().
     */
    public function testCheckControllerExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\mvc\controller::GetClassFullName
     * @todo   Implement testGetClassFullName().
     */
    public function testGetClassFullName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\mvc\controller::IsValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\mvc\controller::GetInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
