<?php

namespace zinux\kernel\caching;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:46.
 */
class xCacheTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var xCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new xCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\caching\xCache::store
     * @todo   Implement testsave().
     */
    public function testsave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::retrieve
     * @todo   Implement testfetch().
     */
    public function testfetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::erase
     * @todo   Implement testdelete().
     */
    public function testdelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::deleteAll(
     * @todo   Implement testdeleteAll().
     */
    public function testdeleteAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::eraseExpired
     * @todo   Implement testdeleteExpired().
     */
    public function testdeleteExpired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::isCached
     * @todo   Implement testIsCached().
     */
    public function testIsCached()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::retrieveAll
     * @todo   Implement testfetchAll().
     */
    public function testfetchAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::getCache
     * @todo   Implement testGetCacheName().
     */
    public function testGetCacheName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::getCacheDirectory
     * @todo   Implement testgetCacheDirectory().
     */
    public function testgetCacheDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::setCache
     * @todo   Implement testSetCacheName().
     */
    public function testSetCacheName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::setCachePath
     * @todo   Implement testSetCachePath().
     */
    public function testSetCachePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\caching\xCache::GetStatisticReportString
     * @todo   Implement testGetStatisticReportString().
     */
    public function testGetStatisticReportString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
