<?php
namespace iMVC\kernel\model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-06 at 00:53:06.
 */
class baseModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var baseModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new baseModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iMVC\kernel\model\baseModel::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\model\baseModel::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\model\baseModel::Dispose
     * @todo   Implement testDispose().
     */
    public function testDispose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\model\baseModel::LoadModel
     * @todo   Implement testLoadModel().
     */
    public function testLoadModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\model\baseModel::IsModelLoaded
     * @todo   Implement testIsModelLoaded().
     */
    public function testIsModelLoaded()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
