<?php

namespace iMVC\exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-04 at 21:35:56.
 */
class invalideOperationExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var invalideOperationException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new invalideOperationException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\exceptions\invalideOperationException::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
