<?php

namespace iMVC\exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-04 at 21:35:55.
 */
class notImplementedExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var notImplementedException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new notImplementedException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\exceptions\notImplementedException::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\exceptions\notImplementedException::SendErrorCode
     * @todo   Implement testSendErrorCode().
     */
    public function testSendErrorCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\exceptions\notImplementedException::GetErrorCode
     * @todo   Implement testGetErrorCode().
     */
    public function testGetErrorCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
