<?php

namespace iMVC\kernel\application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-07 at 06:09:27.
 */
class applicationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\kernel\application\application::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\application\application::Run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\application\application::Shutdown
     * @todo   Implement testShutdown().
     */
    public function testShutdown()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\application\application::Startup
     * @todo   Implement testStartup().
     */
    public function testStartup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
