<?php
namespace iMVC\kernel\routing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-06 at 00:53:07.
 */
class preDispatcherTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var preDispatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new preDispatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::Dispose
     * @todo   Implement testDispose().
     */
    public function testDispose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::Process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::RunBootstraps
     * @todo   Implement testRunBootstraps().
     */
    public function testRunBootstraps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::RunINI
     * @todo   Implement testRunINI().
     */
    public function testRunINI()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\routing\preDispatcher::RunReservedURI
     * @todo   Implement testRunReservedURI().
     */
    public function testRunReservedURI()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
