<?php

namespace iMVC\kernel\caching;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:46.
 */
class sessionCacheTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var sessionCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new sessionCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\kernel\caching\sessionCache::eraseAll
     * @todo   Implement testEraseAll().
     */
    public function testEraseAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\sessionCache::setCachePath
     * @todo   Implement testSetCachePath().
     */
    public function testSetCachePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\sessionCache::getCacheDirectory
     * @todo   Implement testgetCacheDirectory().
     */
    public function testgetCacheDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
