<?php

namespace iMVC\kernel\routing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:48.
 */
class httpRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var httpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new httpRequest("/");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @covers iMVC\kernel\routing\httpRequest::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestSkipped("Skipping test for ".__METHOD__);
    }

}
