<?php

namespace iMVC\kernel\helper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-07 at 06:09:26.
 */
class baseHelperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var baseHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new baseHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers iMVC\kernel\helper\baseHelper::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\helper\baseHelper::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\helper\baseHelper::Dispose
     * @todo   Implement testDispose().
     */
    public function testDispose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\helper\baseHelper::LoadHelper
     * @todo   Implement testLoadHelper().
     */
    public function testLoadHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\helper\baseHelper::IsHelperLoaded
     * @todo   Implement testIsHelperLoaded().
     */
    public function testIsHelperLoaded()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
