<?php
namespace iMVC\kernel\caching;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-06 at 00:53:06.
 */
class cacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iMVC\kernel\caching\cache::isCached
     * @todo   Implement testIsCached().
     */
    public function testIsCached()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::store
     * @todo   Implement testStore().
     */
    public function testStore()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::retrieve
     * @todo   Implement testRetrieve().
     */
    public function testRetrieve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::retrieveAll
     * @todo   Implement testRetrieveAll().
     */
    public function testRetrieveAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::erase
     * @todo   Implement testErase().
     */
    public function testErase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::eraseExpired
     * @todo   Implement testEraseExpired().
     */
    public function testEraseExpired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::eraseAll
     * @todo   Implement testEraseAll().
     */
    public function testEraseAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::getCacheDir
     * @todo   Implement testGetCacheDir().
     */
    public function testGetCacheDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::setCachePath
     * @todo   Implement testSetCachePath().
     */
    public function testSetCachePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::getCachePath
     * @todo   Implement testGetCachePath().
     */
    public function testGetCachePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::setCache
     * @todo   Implement testSetCache().
     */
    public function testSetCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::getCache
     * @todo   Implement testGetCache().
     */
    public function testGetCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::setExtension
     * @todo   Implement testSetExtension().
     */
    public function testSetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iMVC\kernel\caching\cache::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
