<?php

namespace zinux\kernel\routing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 09:47:19.
 */
class postDispatcherTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var postDispatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new postDispatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\routing\postDispatcher::Process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        $this->assertTrue(true);
    }

}
