<?php

namespace zinux\kernel\utilities;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:46.
 */
class fileSystemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var fileSystem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new fileSystem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\utilities\fileSystem::GetCaches
     * @todo   Implement testGetCaches().
     */
    public function testGetCaches()
    {
        $this->assertTrue(true);
    }

    /**
     * @covers zinux\kernel\utilities\fileSystem::resolve_path
     * @todo   Implement testResolve_path().
     */
    public function testResolve_path()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers zinux\kernel\utilities\fileSystem::Initiate
     * @todo   Implement testInitiate().
     */
    public function testInitiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
